### ISSUE TITLE
Needs review/feedback

### ISSUE THREAD

**Issue by joshgoebel** [base16-project/base17#1]
@belak @JamyGolden 

Could you both please read `style_guide.md` and `schema_spec.md` and provide any thoughts?  Right now:

- style guide is intended to be JUST styling rules / guidelines / hints (but with a full example)
- schema_spec is intended to explain details of the YAML format itself

Looking for feedback on the spec itself from an schema implementors perspective - ie, if everything is clear, makes sense, and you could set down and make a scheme after reading the spec...

Previous `schema_spec` is found in builder, but we had discussed moving it back out again to simplify the builder spec. 

- If we're still ok with this I think it needs to be fleshed out a lot more (should I do this?)
- If we're not ok with this then, this info... well we need a plan.

---

- Should upgrading be moved out of the style guide into a sep `UPGRADE` document?
- Perhaps addendums should just become headers in the main document?

**Comment by joshgoebel** [comment]
If you have broad sweeping changes/concerns I'd prefer to discuss them, but if you just want to fix/tidy up some things feel free to open a PR.

**Comment by mikeduminy** [comment]
`diff_deleted` is used as an example override. Where could one find the list of all possible overrides?

**Comment by joshgoebel** [comment]
The palette table in the spec is intended to be exhaustive unless we keep adding then we likely need a separate list.

**Comment by joshgoebel** [comment]
But we are still in the middle of discussing - you can find the thread over in the main project repository.

**Comment by bspellmeyer** [comment]
Looking at the style guide, the scheme spec and the builder requirements, I find the spec somewhat confusing.

The style guide states that a theme author is still [limited to 16 colors](https://github.com/base16-project/base17/blob/main/style_guide.md#you-are-still-limited-to-a-max-of-16-colors). But the spec does not enforce any limit on the number of colors used.

Take the following color scheme:

```yaml
scheme: "does-not-build"
author: "John Doe"

variables:
  $red: "#FF0000"

customize:
  diff_deleted: $red

default:
  base00: "#1C2023"
  base01: "#393F45"
  base02: "#565E65"
  base03: "#747C84"
  base04: "#ADB3BA"
  base05: "#C7CCD1"
  base06: "#DFE2E5"
  base07: "#F3F4F5"
  base08: "#000000"
  base09: "#000011"
  base0A: "#001122"
  base0B: "#112233"
  base0C: "#223344"
  base0D: "#334455"
  base0E: "#445566"
  base0F: "#556677"
``` 

This scheme defines 17 colors: 16 base colors and 1 color variable `$red` used for the `diff_deleted` customization. All colors are unique. Therefore, the scheme is invalid and the builder should throw an error when trying to parse it.

Maybe the spec could stick closer to the original. Define the 16 base colors, then name them for readability, allow customizations. E.g.

```yaml
scheme: "might-build"
author: "John Doe"

default:
  base00: "#FF0000"
  base01: "#393F45"
  base02: "#565E65"
  base03: "#747C84"
  base04: "#ADB3BA"
  base05: "#C7CCD1"
  base06: "#DFE2E5"
  base07: "#F3F4F5"
  base08: "#000000"
  base09: "#000011"
  base0A: "#001122"
  base0B: "#112233"
  base0C: "#223344"
  base0D: "#334455"
  base0E: "#445566"
  base0F: "#556677"

aliases:
  $black: base08
  $red: base00

overrides:
  diff_added: base03
  diff_deleted: $red
```

No hex codes would be allowed for `aliases` and `overrides`.

What do you think?
